## Setup
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

## Mod Metadata
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

## Mod Dependencies
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "computercraft"
mandatory = true
versionRange = "${cct_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "tardim"
mandatory = true
versionRange = "${tardim_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "curios"
mandatory = true
versionRange = "${curios_version_range}"
ordering = "AFTER"
side = "BOTH"